name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run tests
        run: |
          docker compose build
          docker compose run --rm backend-tests
          docker compose run --rm frontend-tests
